### ISSUE TITLE
Use only spatial forecast rates to run spatial test

### ISSUE THREAD

**Issue by khawajasim** [SCECcode/pycsep#120]
We need to have a complete spatio-magnitude forecast even to calculate S test. Most of the times I am only playing with spatial forecast rates. The testing functions should be flexible enough to accept only one column for forecast and run spatial test. The magnitude bin in that case can be [5.95].

**Comment by wsavran** [comment]
hi @khawajasim, i would recommend that you write a "custom loader function" that properly reads in a spatial forecast. we can consider the spatial forecast as a standard forecast with a single magnitude bin.

 all we must do is reshape the 1d array of rates into an (n,1) array of rates using the following numpy command:
```python
a.reshape(-1,1) # to create the (n,1) array
```
assuming that `a` is the numpy array that stores the spatial rates. 

the custom loader function should return a tuple that contains
```
output[0] = forecast data 
output[1] = spatial region object
output[2] = magnitude bin edges
```

**Comment by wsavran** [comment]
Did the reshaping solution work? If so, I'd like to close this issue.

**Comment by khawajasim** [comment]
Yes it worked. So I am closing it.
