### ISSUE TITLE
Global elipse projections not compatible with central_longitude argument 

### ISSUE THREAD

**Issue by pabloitu** [SCECcode/pycsep#144]
https://github.com/SCECcode/pycsep/blob/f8f75a99431928b25a98f3585fba9ca04fda466e/examples/tutorials/plot_customizations.py#L120

Robinson (Ellipse) projections for global forecasts are not working when central_longitude is passed as argument. This is due to cartopy version update.

**Comment by wsavran** [comment]
@pabloitu do we have a fix for this issue? see #148 for reasons i dont think we can pin cartopy=0.19.0
