### ISSUE TITLE
proj cartopy dependency error

### ISSUE THREAD

**Issue by pabloitu** [SCECcode/pycsep#148]
Dependency issue with latest cartopy updates (> 0.20.0) that points to newer version of proj (8.0.0), which in turn is not available through apt (7.0.0) as suggested in our installation guide (same issue on scitools/cartopy#1912).  Pip finally installs automatically cartopy==0.19.0.  This makes me wonder if we should freeze some dependencies in the requirements.txt, e.g. cartopy==19.0.0, and update them as we release new pycsep versions?

**Comment by wsavran** [comment]
yeah good point on this, there is an issue with cartopy 0.19.0 that uses stale URLs for some basemap downloads. see issue #141 here. i dont think we can pin that otherwise we might run into that same issue.

the proj8 issue only comes up if people want to install via pip, which means that proj8 can be installed via source or using `conda` with no issues. 

i'm not sure a good solution here. any thoughts?

**Comment by pabloitu** [comment]
Sorry, this is actually almost duplicate. Apparently `Proj` had been quite slow to update the apt, but cartopy may try to rely in `pyproj` instead of `Proj` at all SciTools/cartopy/issues/1832. For now they pinned the version of `Proj` to > 8.0.0.  Being honest, it is always a mess dealing with proj and gdal libs. 

Within pip, the solution is to install proj by source in my local machine. Conda works as a charm, unless it attempt to use inherited global packages (Any idea how to install pycsep by forcing to use the latest dependecies versions within conda forge?).  

I believe you are right, and is better to wait either `Proj` updating the apt repository, or cartopy getting independent of it.

**Comment by wsavran** [comment]
this is definitely a challenge with `anaconda` and part of the reason that i prefer the `miniconda` distribution instead. my approach is generally to always use virtual environments and to routinely update my conda packages using `conda update --all`. 

i try to create an environment to start that is very lightweight eg, from miniconda and just install the deps within that environment.

**Comment by wsavran** [comment]
im looking through [here](https://docs.conda.io/projects/conda/en/latest/commands/install.html?highlight=force-reinstall). maybe there is an option that would do what you want. to be honest, ive never tested these options myself so i can't vouch for them.
