### ISSUE TITLE
standardize plotting arguments

### ISSUE THREAD

**Issue by wsavran** [SCECcode/pycsep#153]
we should have a way to standardize the plotting arguments for each plotting function. one solution would be to define a decorator that wraps the function and provides a list of the plotting arguments with their defaults to each function. 

something like
```python
@provide_plot_args
def plot_something(arg1, arg2):
    # we have access to plot_args here
    pass
```

@pabloitu any thoughts on the best way to do this?

**Comment by wsavran** [comment]
this idea needs some more thought, but it would be nice to have an easy way of passing a set of 'default' plotting arguments to each function by default without copying them in each function.

**Comment by pabloitu** [comment]
True, I like the idea. I also believe that beside standarizing the args names, we should name them as identically as possible to matplotlib. 
I have a q: with the wrapper, do you intend to change the plot_something plotting args from a dict() to **kwargs instead? Maybe this could be also a solution to non-relevant args (like title_fontsize) to be passed quickly to matplotlib, if arguments are not repeated)
