### ISSUE TITLE
region borders misplot for concave regions

### ISSUE THREAD

**Issue by pabloitu** [SCECcode/pycsep#197]
The boundaries of a region fails to plot correctly when the region is concave in the x axis (a horizontal line touches the region twice). 
See northern edge of NZ, or two small cells in the eastern edge:

<img src="https://user-images.githubusercontent.com/69042881/191048761-4aac3ca5-82b4-4b5f-9486-331a0d60a3ca.png" height="300" />

will try a quick solution using shapely (merge cell polys and then get boundary)

**Comment by wsavran** [comment]
Good catch! Do you have any idea why this is happening or better yet, any ideas for a fix?

**Comment by pabloitu** [comment]
I would try to use shapely (pygeos) to find a quick boundary extraction instead of coding it myself. Will take a look at it
