### ISSUE TITLE
forecast load_ascii creates non-valid region polygons 

### ISSUE THREAD

**Issue by pabloitu** [SCECcode/pycsep#200]
load_ascii creates self-intersection polygons for the cells that constitutes a region, i.e. ordering of nodes makes crossing edges |\|, instead of clockwise or counter-clockwise.  
```
forecast = csep.load_gridded_forecast(datasets.helmstetter_mainshock_fname)
forecast.polygons[0].points
>>>  ((-125.4, 40.1), (-125.4, 40.2), (-125.3, 40.1), (-125.3, 40.2))
```

**Comment by wsavran** [comment]
is this what was causing the issue with shapely?

**Comment by pabloitu** [comment]
yes. I guess non-selfintersecting polygons is irrelevant for pycsep functionality, but I guess if we want to extend some CartesianGrid2D features, it could help.
