### ISSUE TITLE
Error loading historical catalog

### ISSUE THREAD

**Issue by allenos-usgs** [SCECcode/pycsep#223]
I've been having problems loading in a csv catalog that goes back to the year 1700.

I've been loading it in like so:
![image](https://user-images.githubusercontent.com/63483102/235172072-fff1fbbb-f02e-430d-addc-ce72d23677b7.png)
 
Then I get the following traceback:
![image](https://user-images.githubusercontent.com/63483102/235172524-ac9ca473-f234-49f8-b5e8-fb5338e7d141.png)

I think I've traced the issue to this function in time_utils.py, which seems to have a baseline of 1970:
![image](https://user-images.githubusercontent.com/63483102/235172665-9d3df819-3441-4729-80e2-2c5b4e790086.png)

Because if I trim my test catalog so that it starts in 1970 instead of 1700, then it's able to be loaded in no problem. And if I go back to using the entire catalog, but in the function I change 1970 to 1700, then I get the following: 
![image](https://user-images.githubusercontent.com/63483102/235172970-6197d70c-b5b9-4725-a3a8-1f5b32706519.png)

It loads in the entire catalog, but now it seems to think it starts in 1970 and ends ~270 years in the future. Any help with getting it to read in the entire catalog with the correct years would be much appreciated!

Thanks,
Andrea

**Comment by wsavran** [comment]
thanks @allenos-usgs. I'll look into this next week and see what the issue is loading historical catalogs.

**Comment by wsavran** [comment]
@allenos-usgs can you upload the catalog that you are having this problem with. @pabloitu tested this out inline and the epoch times just returned negative numbers. this was done in-line, so it might have something to do with the reader. in the mean time I will create a test catalog and try and reproduce.

**Comment by allenos-usgs** [comment]
Sure thing, here's the catalog. 
[csep_test_cat2.csv](https://github.com/SCECcode/pycsep/files/11454861/csep_test_cat2.csv)

**Comment by allenos-usgs** [comment]
Hi @pabloitu , thanks for looking into it. I tried to work with the JSON version of the catalog that you sent, but I seem to be having a similar sort of problem when I try to load the catalog. Here's the traceback:
![image](https://github.com/SCECcode/pycsep/assets/63483102/52dfe2a4-1bea-4886-a778-d267d98247fd)

Perhaps the same sort of windows issue?

**Comment by pabloitu** [comment]
yes, was the same bug :(!   but fixed it in #229, we need a short review and try to commit to main as quick as possible.

**Comment by fabiolsilva** [comment]
This should now be fixed, with latest merge of #230 into the main branch.
