### ISSUE TITLE
use mamba for release ci/cd on pypi pipeline

### ISSUE THREAD

**Issue by wsavran** [SCECcode/pycsep#234]
this is a 2 parter:

1. we should use mamba for the [publish-pypi.yml](https://github.com/SCECcode/pycsep/blob/master/.github/workflows/publish-pypi.yml) pipeline
2. we need to update the documentation to reflect that users will need to manually install the documentation packages. the best way to do this is probably to create a ```requirements_docs.yml``` and let them know they need to use that to install the `sphinx` dependencies.

**Comment by pabloitu** [comment]
- The [publish-pypi.yml](https://github.com/SCECcode/pycsep/blob/master/.github/workflows/publish-pypi.yml) pipeline is already updated with mamba. Was the latest release automatically published in pypi using mamba @fabiolsilva , @pjmaechling?  

- @wsavran I believe you already wrote in the contribution instructions  (https://github.com/SCECcode/pycsep/blob/main/CONTRIBUTING.md#developer-installation) to install pycsep with `pip install -e .[all]`.  That should install all the docs dependencies, which are specified in pycsep `setup.py`.   Will make an update in the docs, where that is missing.
