### ISSUE TITLE
Greeting

### ISSUE THREAD

**Issue by seiszhang** [SCECcode/pycsep#29]
Hello everyone, I now working in IEFCEA and is also member of China CSEP2 team. In previous days I have focused our CSEP2 program all the time and these days it seems good for the progress you have done. So what kinds of help or example data of China can I suplly for you for your test in this coding program? I also expect to cooperate into our team, however, the coding ability maybe cannot satisfy your need. But I can do plot some figure or do some data analysis if you need. BTW, is the PyCSEP program here can be installed in my unbuntu pc and do some forecast and evaluation? Do the scripts contains the forecast model or algrithm? Sorry I have not see the details of the scripts. Thanks for your guide.

**Comment by wsavran** [comment]
Hi @seiszhang, nice to meet you, and thanks for reaching out. Right now we are working on the getting the pycsep package ready for release. We will be giving some tutorials on how the code works in about a month. Yes, the package can be installed in ubuntu, but it's in a state of rapid development so things will be changing over the next month. 

What catalog format do you use for the Chinese seismic network?

**Comment by seiszhang** [comment]
> Hi @seiszhang, nice to meet you, and thanks for reaching out. Right now we are working on the getting the pycsep package ready for release. We will be giving some tutorials on how the code works in about a month. Yes, the package can be installed in ubuntu, but it's in a state of rapid development so things will be changing over the next month.
> 
> What catalog format do you use for the Chinese seismic network?

The earthquake catalog download from Chinese seismic network has the format as follow:

                    全国地震正式报目录查询结果

   日期 时间 纬度 精度 深度 震级类型 震级值 位号 地震类型 参考地名                                                                       
2008-10-01 01:05:26.24  37.610   76.098 136 ML     2.1 65 eq 新疆维吾尔自治区喀什地区塔什库尔干塔吉克自治县                                    
2008-10-01 01:07:18.70  32.990  105.562  12 ML     1.6 62    甘肃武都县                                                                        
2008-10-01 01:14:19.83  30.815  103.271  18 ML     2.2 51    四川崇州市   

It has the essential information of an earthquake event(Year-month-day hour-minate-second Lat. Log. dep. type M network_code events_type place). For the easy use in my research, I always transfer it into the regular format as:
2008 01 01 01 18 34.70  27.520  103.880  1.8  05 
2008 01 01 01 22 00.30  40.320   77.770  1.4  31 
2008 01 01 01 31 32.10  39.430   76.880  1.5  29 
2008 01 01 02 37 43.10  21.850  111.950  1.0  00
And I can input or read it easily into a laguage software. Maybe it need a simple  format conversion like this before the CENC cat can used into pyCSEP. Another point, is the catalog input and update process in pyCSEP a automatic way or a manual operation? Because the CENC catalog above can only be obtained from the seismic networks in China, not the public netwoks, so it maybe need a automatic script to update it before used into the pySCEP. How about the cases of other catalog you have tested?

**Comment by wsavran** [comment]
Yes this catalog format can be easily read into PyCSEP, but it would require writing a function that reads that data and returns a tuple formatted properly. If you look at the function [csep_ascii()](https://github.com/SCECcode/csep2/blob/ed06ee934fbd373d2d9b30907ed8444533f41ddc/csep/utils/readers.py#L396) you can see an example of how the data should be formatted. 

I'd be happy to help with this in the next couple of weeks. I think we can easily parse the first format you listed. Are those dates in UTC time or local china time?

**Comment by seiszhang** [comment]
That's good. The dates  in CENC catalog is local China time. What can I give a help to pyCSEP next? Should I send you a example catalog to test? Because the forecast result outputed from different models should have a certain format, for example, it should have the same grid size for the probability result, so how the test method in pycsep to evaluate the forecast result of third-part models? Should the third-part model have to be modified to follow the pyCSEP standard?

**Comment by wsavran** [comment]
sorry for the late reply @seiszhang. yes, the forecasts should have a particular format which can be seen in the [documentation ](https://cseptesting.org). this url may change in the next couple weeks, but i will update it here when/if that happens. do you have any models that are ready to be put under test?

**Comment by wsavran** [comment]
@seiszhang thank you for reaching out, but as of now i will close this issue. pleae feel free to contact us with any additional questions!
