### ISSUE TITLE
the INGV-ercmt catalog reader confuses mw columns with depth in some events

### ISSUE THREAD

**Issue by pabloitu** [SCECcode/pycsep#38]
(Pending fix) The catalog parser does not separate appropriately every column of the catalog, sometimes mixing magnitudes with depths
https://github.com/SCECcode/pycsep/blob/d7d9c09f6906de22d3c46d79c54d3bfa9b45f398/csep/utils/readers.py#L486

e.g. event 1060 of  (pycsep/tests/artifacts/Testing/ingv_rcmt-catalogs/full.csv)

**Comment by wsavran** [comment]
@pabloitu assigning this one to you. let me know if you need a hand

**Comment by pabloitu** [comment]
Yes, this was fixed in the last pull request (which includes the ingv_horus reader as well). Sorry the confusion

**Comment by wsavran** [comment]
closed with #40 @pabloitu let me know if we need to revisit this
