### ISSUE TITLE
poisson_evaluations likelihood_test out of bounds error

### ISSUE THREAD

**Issue by kirstybayliss** [SCECcode/pycsep#43]
I can run the magnitude, number and spatial tests from poisson_evaluations without issue, but the likelihood_test and conditional_likelihood_test both give the same error when I try to run them with the example (gridded) forecast (called forecast_ex here).

```python
IndexError                                Traceback (most recent call last)
<ipython-input-85-fdd092fbc693> in <module>
----> 1 llhood_test_result_ex = poisson.conditional_likelihood_test(forecast_ex, catalog)
      
c:\users\kirst\pycsep\csep\core\poisson_evaluations.py in conditional_likelihood_test(gridded_forecast, observed_catalog, num_simulations, seed, random_numbers, verbose)
    175 
    176     # simply call likelihood test on catalog data and forecast
--> 177     qs, obs_ll, simulated_ll = _poisson_likelihood_test(gridded_forecast.data, gridded_catalog_data,
    178                                                         num_simulations=num_simulations, seed=seed, random_numbers=random_numbers,
    179                                                         use_observed_counts=True,

c:\users\kirst\pycsep\csep\core\poisson_evaluations.py in _poisson_likelihood_test(forecast_data, observed_data, num_simulations, random_numbers, seed, use_observed_counts, verbose)
    511     # these operations perform copies
    512     observed_data_nonzero = observed_data.ravel()[target_idx]
--> 513     target_event_forecast = log_bin_expectations[target_idx] * observed_data_nonzero
    514 
    515     # main simulation step in this loop

IndexError: index 350244 is out of bounds for axis 0 with size 314962
```
I loaded the catalog using the example in the documentation. I filtered the catalog using `catalog.filter_spatial(forecast_ex.region)` and confirmed that the number of spatial grid cells was correct. I think there are too many magnitude bins in the `gridded_catalog_data`, which seems to have 65 if I go by the shape of the array result from `catalog.spatial_magnitude_counts()`. 
From a bit of digging, this seems to come from `forecast_ex.region.magnitudes` which starts at 2.5 giving 65 bins, while the actual data in the example start from magnitude 4.95 giving 41 magnitude bins, and there are 7682 spatial cells which would line up with the point at which the error occurs.

**Comment by wsavran** [comment]
you are exactly correct about the root of the issue. i've made the appropriate change in #44

**Comment by wsavran** [comment]
closing this issue with #44
