### ISSUE TITLE
Plot for W-test

### ISSUE THREAD

**Issue by bayonato89** [SCECcode/pycsep#48]
Hi Bill,

Here, I am following the discussion on W-test results. For forecasting areas with a small number of earthquakes, it might be important to run W-tests and be able to visualize the results.

Thanks,

Toño

**Comment by wsavran** [comment]
thanks for the suggestion! i will try and add this feature. if you'd like to take a stab at adding this, let me know. it would be a good first issue to tackle.

**Comment by wsavran** [comment]
summary of our thoughts... only plot the w-test result in the case where it would help to confirm the t-test. this should use a descriptive marker (like an 'x') below the error bars from the t-test. for most cases, the w and t-test are in agreement.

**Comment by wsavran** [comment]
@bayonato89 please reference this issue by typing "#48" (without the quotes) when you open a pull-request.
