### ISSUE TITLE
Error when loading GCMT 'ndk' catalog.

### ISSUE THREAD

**Issue by baobaohan** [SCECcode/pycsep#51]
Hi all,

I would like to ask you a small question about csep.load_catalog() function. So, I'm trying to load a GCMT catalog but encountered this problem (see the screenshot below). A copy of the 'ndk' file that I'm trying to load is also attached (a suffix '.txt' is added to the file name to upload, so make sure you delete it when trying to reproduce the error).
[GCMT_temp.ndk.txt](https://github.com/SCECcode/pycsep/files/5490017/GCMT_temp.ndk.txt)

![Screen Shot 2020-11-04 at 10 54 22 AM](https://user-images.githubusercontent.com/33332247/98157149-c0468080-1e8d-11eb-9411-a6815eb9f450.png)

Looks like it occurred when .../csep/core/catalogs.py [_get_catalog_as_ndarray(self)] trying to convert a line data/strings but has a length mismatch. 

Any kind of help is much appreciated.

Han

**Comment by wsavran** [comment]
it looks to be an issue with how dates and times used to be handled. how did you install the source code of the software? this appears to be happening from an old version of the code. the fix should already exist on the github version, and will be pushed to both pypi and conda-forge shortly. since you are an early user of the package i would recommend following [these](https://github.com/SCECcode/pycsep/blob/master/CONTRIBUTING.md) installation instructions, because they will allow you to have the most up-to-date code. Also you will be able to easily make contributions to the package if you see fit.

**Comment by baobaohan** [comment]
Thanks for the quick response! 

I installed it two days ago from the documentation page: https://cseptesting.org/getting_started/installing.html

Let me try to reinstall now.

**Comment by wsavran** [comment]
right on, i definitely think that is the issue. im planning to make a new release in the next week or so that will have this fix included. either way using the developer's installation is recommened. just make sure to enable the conda environment `csep-dev`

**Comment by baobaohan** [comment]
Bill, thanks for the help. I'm now able to load the ndk catalog.

However, when playing with the core.load_catalog() function, the option " format='csep' " will output an error. I'm wondering if this not the right way to do it (i.e. the right way is to stick with the 'native' option or is it a bug. You may see the attached screenshot below for more info) 

Thanks！

![Screen Shot 2020-11-04 at 12 04 05 PM](https://user-images.githubusercontent.com/33332247/98162434-33ec8b80-1e96-11eb-8553-6fc3499f276c.png)
![Screen Shot 2020-11-04 at 12 04 15 PM](https://user-images.githubusercontent.com/33332247/98162441-36e77c00-1e96-11eb-80e1-be56bd9e42cd.png)

**Comment by wsavran** [comment]
glad to hear that its working. in this case the 'native' and 'csep' formats are the same; however, this should not throw an error. thanks for uncovering this behavior. i will patch a fix for this later today.

**Comment by baobaohan** [comment]
My pleasure. Thanks, Bill! 👍

**Comment by wsavran** [comment]
@baobaohan if you pull the latest from the master branch it should fix the issue you found. either way, the catalog should now work as expected.
