### ISSUE TITLE
Error when plotting a forecast model

### ISSUE THREAD

**Issue by baobaohan** [SCECcode/pycsep#54]
Below I show the error output when trying to plot the example forecast model "helmstetter_mainshock" as shown in the PyCSEP documentation page:

Before I switch to the most recent version of PyCSEP, I did this example before with no problem.
![Screen Shot 2020-11-06 at 10 20 34 AM](https://user-images.githubusercontent.com/33332247/98409614-09323c80-2028-11eb-8f98-3f34c07764ca.png)

+Han

**Comment by wsavran** [comment]
ill look into this. i'm not sure this error is coming from pycsep, it looks more like its coming from the interplay between matplotlib and cartopy. can you let me know which version of matplotlib and cartopy you are using?

**Comment by baobaohan** [comment]
matplotlib: 3.3.2                    
matplotlib-base: 3.3.2
cartopy: 0.17.0 

I also attached the entire conda list below, just in case you need it. Thanks, Bill.

[condaList.txt](https://github.com/SCECcode/pycsep/files/5503492/condaList.txt)

**Comment by baobaohan** [comment]
Tried to explore a little bit based on the suspicion of the matplotlib or cartopy version.

As you see the cartopy version I posted above is 0.17.0.  I then tried the plotting with a cartopy version of 0.18.0

Here is what I got below: no errors but the figure is not properly displayed. Hope it helps a little bit. 
![Screen Shot 2020-11-06 at 2 42 36 PM](https://user-images.githubusercontent.com/33332247/98421690-c334a300-203e-11eb-943c-ed52e3c62af7.png)

**Comment by baobaohan** [comment]
I want to add that the plot of the example forecast (helmstetter_mainshock) is good.

**Comment by wsavran** [comment]
ok i  will look into this issue. i think the gridded forecast plot might have an issue for global forecasts, which might require a code change. in the mean time, you can plot the data using your own function by calling `forecasts.spatial_counts(cartesian=True)` to return a 2D numpy array that represents the counts in space. i might have an example of a function that you can use to plot this global forecast.

**Comment by wsavran** [comment]
```
def plot_global_forecast(forecast, catalog=None, name=None):
    """
    Creates global plot from a forecast using a Robin projection. This should be used as a quick and dirty plot and probably
    will not suffice for publication quality figures.

    Args:
        forecast (csep.core.forecasts.MarkedGriddedDataSet): marked gridded data set
        catalog (csep.core.data.AbstractBaseCatalog):  data base class
        name (str): name of the data

    Returns:
        axes

    """
    fig, ax = pyplot.subplots(figsize=(18,11))
    m = Basemap(projection='robin', lon_0= -180, resolution='c')
    m.drawcoastlines(color = 'lightgrey', linewidth = 1.5)
    m.drawparallels(numpy.arange(-90.,120.,15.), labels=[1,1,0,1], linewidth= 0.0, fontsize = 13)
    m.drawmeridians(numpy.arange(0.,360.,40.), labels=[1,1,1,1], linewidth= 0.0, fontsize = 13)
    x, y = m(forecast.get_longitudes(), forecast.get_longitudes())
    cbar = ax.scatter(x, y, s = 2, c = numpy.log10(forecast.spatial_counts()), cmap = 'inferno', edgecolor='')
    a = fig.colorbar(cbar, orientation = 'horizontal', shrink = 0.5, pad = 0.01)
    if catalog is not None:
        x, y = m(catalog.get_longitudes(), catalog.get_latitudes())
        ax.scatter(x, y, color='black')
    a.ax.tick_params(labelsize = 14)
    a.ax.tick_params(labelsize = 14)
    if name is None:
        name='Global Forecast'
    a.set_label('{}\nlog$_{{10}}$(EQs / (0.1$^o$ x 0.1$^o$)'.format(name), size = 18)
    return ax
```

you can try this function but it will require you to install matplotlib Basemap which has been deprecated in favor of Cartopy. If you prefer, you can just use this as a guideline to make your own plotting function using Cartopy.

**Comment by baobaohan** [comment]
Many thanks for sharing the code snippet. Will try it!

**Comment by baobaohan** [comment]
Hi Bill,

Here is the code of the global plot translated to Cartopy (everything it does is almost the same as it was before and an output example is attached just for your reference
![Uploading GEAR _with_Seismicity_2014-2019.png…]()
):

```
import numpy as np
import cartopy.crs as ccrs
import matplotlib.pyplot as plt


def plot_global_forecast(forecast, catalog=None, name=None, resolution='110m', savepdf=False, savepng=False):
    """
    Creates global plot from a forecast using a Robin projection. This should be used as a quick and dirty plot and probably
    will not suffice for publication quality figures.

    Args:
        forecast (csep.core.forecasts.MarkedGriddedDataSet): marked gridded data set
        catalog (csep.core.data.AbstractBaseCatalog):  data base class
        name (str): name of the data
        resolution (str): in meter

    Returns:
        axes

    """
    fig, ax = plt.subplots(figsize=(18,11))
    m = plt.axes(projection=ccrs.Robinson(central_longitude=-180))
    m.set_global()
    m.coastlines(resolution=resolution, color='lightgrey')
    m.gridlines(draw_labels=False)
#     m.gridlines(draw_labels=True, xlocator=np.arange(-90.,120.,15.), ylocator=np.arange(0.,360.,40.))
    
    cbar = m.scatter(forecast.get_longitudes(), forecast.get_latitudes(), c = np.log10(forecast.spatial_counts()),
                     s = 2, cmap = 'inferno', transform=ccrs.PlateCarree())
    a = fig.colorbar(cbar, orientation = 'horizontal', shrink = 0.5, pad = 0.01)
    a.ax.tick_params(labelsize = 14)
    a.ax.tick_params(labelsize = 14)
    
    if catalog is not None:
        m.scatter(catalog.get_longitudes(), catalog.get_latitudes(), s=0.007*catalog.get_magnitudes()**5,
                  color='lightgray',edgecolors='black', linewidths=1, transform=ccrs.PlateCarree())
    
    
    if name is None:
        name='Global Forecast'
    a.set_label('{}\nlog$_{{10}}$(EQs / (0.1$^o$ x 0.1$^o$)'.format(name), size = 18)
    
    if savepdf:
        outFile = "{}.pdf".format(name)
        plt.savefig(outFile,format='pdf')
    if savepng:
        outFile = "{}.png".format(name)
        plt.savefig(outFile,format='png')
    return fig, ax
```

I added some saving functions only for my purpose. (saving pdf is so crazy big and time consuming)

There is only one more thing that need to be solved: the label of the coordinate grids for ROBINSON projection are not available for the latest Cartopy version. I don't have a quick solve.

**Comment by wsavran** [comment]
figure looks great, but surprised about the lat/lon labels. that is definitely worth an ask over @cartopy .

**Comment by baobaohan** [comment]
It's a pending issue now and are about to be solved in recent updates.
You can refer to this link: https://github.com/SciTools/cartopy/issues/1609

**Comment by wsavran** [comment]
im closing for now @baobaohan. please re-open a new issue if there are any more troubles.
