### ISSUE TITLE
'one_sided_lower option' of the poisson_plot function not functioning with obs_value larger than predicted range

### ISSUE THREAD

**Issue by baobaohan** [SCECcode/pycsep#56]
Hi Bill,

Just want to report a small issue. The two plots below shows a comparison of figure with 'one_sided_lower=True' and the other with 'one_sided_lower=False'. No rush, tho. 

![Screen Shot 2020-11-11 at 4 26 05 PM](https://user-images.githubusercontent.com/33332247/98879552-af23e380-243a-11eb-8320-fdfe0a3c4b10.png)

**Comment by wsavran** [comment]
i just pushed a hotfix to master to address this issue. try again. the top plot should be the same and in the bottom plot the green squares should be red circles.

**Comment by baobaohan** [comment]
That was fast! Thx!

**Comment by wsavran** [comment]
no problem! let me know if that fix worked for you!

**Comment by baobaohan** [comment]
Got an error as below. Any idea?
![Screen Shot 2020-11-11 at 5 23 43 PM](https://user-images.githubusercontent.com/33332247/98883110-b0f1a500-2442-11eb-9415-56eaf39626fb.png)

**Comment by wsavran** [comment]
that function should only return an ax not a fig, ax try this 
`ax = plots.plot_poisson_consistency_test(...)`

**Comment by baobaohan** [comment]
Opps. My bad. I made a slight change of the code before so that I can save the fig. Ok so it's still the same.

I did fork into my own github account. 
And in terminal I run 
```
git checkout csep     
git fetch origin       
git merge origin/master
```

**Comment by wsavran** [comment]
are you trackign the upstream repository. can you show me the output when you type 
`git remote -v` into your console

**Comment by baobaohan** [comment]
It does not look right... lol
![Screen Shot 2020-11-11 at 5 42 48 PM](https://user-images.githubusercontent.com/33332247/98884638-5574e680-2445-11eb-8c0e-2645b59f0355.png)

**Comment by wsavran** [comment]
you'll have to be in one of the code directories wherever you cloned the repository. probably just in the wrong working directory.

**Comment by baobaohan** [comment]
Got it. Here it is. (sorry I'm still learning the git)

![Screen Shot 2020-11-11 at 5 47 31 PM](https://user-images.githubusercontent.com/33332247/98884980-05e2ea80-2446-11eb-8fdc-296af0257747.png)

**Comment by wsavran** [comment]
im not sure exactly how you have the repo set up on your end, so i'm not sure why you are running `git checkout csep` 
but what you did doesn't look like its going to pull the latest chagnes from upstream. what is the `git checkout csep` doing for you?

you want to run
`git fetch upstream`
`git merge upstream/master master`

**Comment by baobaohan** [comment]
Works now! Thanks a lot! And lesson learned!

**Comment by wsavran** [comment]
glad to hear it. just to confirm the plots worked?

also, this is a bit more complicated bc you used the developer's installation which would allow you to make changes to your copy of the repository at 'origin' and then create a pull request to get them in the 'upstream' branch.

**Comment by baobaohan** [comment]
Yeah, it works!

![Screen Shot 2020-11-11 at 6 05 33 PM](https://user-images.githubusercontent.com/33332247/98886239-81459b80-2448-11eb-8552-306369ddc2e8.png)

What does that mean? Does that means every time I make changes locally, it will create a pull request?

**Comment by wsavran** [comment]
great im closing this issue.

it means that you have the option to create a pull request with any changes that you make locally. its worth reading a bit about git forks to understand what is going on but i can try and summarize the basics here. 

the fork basically just creates a copy you own that is linked to the upstream repository saved a github/SCECCode/pycsep. you can push changes at will to your local copy, but you will have the option to create pull requests taht allow those changes to propagate to the upstream copy of the repo. 

when/if you get to that point open an issue and i can help you set everything up

**Comment by baobaohan** [comment]
Bill, thanks a lot. I will for sure get myself more prepared on the git routines. And I'd love to contribute as I enjoy doing so. To be more specific, I'm planning to save the first three months of next year to mainly work on the global forecast model and am looking forward to contribute much more during that time, if I'm capable.
Also, I've got the I_1 success score done on my own end. If you need it, I can send it to you. If not in rush, I probably can pull the request later.
Thanks, again.
