### ISSUE TITLE
bounding box grid forecast

### ISSUE THREAD

**Issue by pabloitu** [SCECcode/pycsep#58]
The bounding box of the class CartesianGrid2D (get_bbox) returns the extent of region lowerleft-corners, rather than the extent of the forecast (including topright). Should its behavior be like that?. To reproduce

```
import csep
from csep.utils import datasets
import numpy

forecast = csep.load_gridded_forecast(datasets.helmstetter_mainshock_fname,
                                      name='helmstetter_mainshock')
bbox_forecast = forecast.region.get_bbox()

array_ = numpy.genfromtxt(datasets.helmstetter_mainshock_fname) 
bbox_dat = (array_[:,0].min(), array_[:,1].max(), array_[:,2].min(), array_[:,3].max()) 

print(bbox_forecast)
print(bbox_dat)
```

Tracked to here
https://github.com/SCECcode/pycsep/blob/1fa6b26e6215060621a539022a27281470b4c6b6/csep/core/regions.py#L630-L632

But when I look how `CartesianGrid2D.xs` and `ys` are defined in L730,
https://github.com/SCECcode/pycsep/blob/1fa6b26e6215060621a539022a27281470b4c6b6/csep/core/regions.py#L703
 I see that it was intended that the grid extends one more away from the number of cells. For instance, this gives the same result
```
forecast.spatial_counts(cartesian=True).shape == (forecast.region.ys.shape[0], forecast.region.xs.shape[0])
```
Would it be a precision issue?

For the plots.plot_spatial_dataset(), it does not plot the last lat/lon of the CartesianGrid. Although, this could be bypassed quickly inline that plotting function, but I prefer to make sure.

**Comment by wsavran** [comment]
You are correct that the bounding box reporting the lower left node of the grid. This is because the bounding box is used to compute the index of a given (lat,lon) pair and determine the index of the region. 

I'm not sure I follow exactly the plotting issue you are seeing here. If the bounding box extends past the forecast, those additional cells will be masked and not returned when the cartesian argument is supplied to the `spatial_counts` function. Is this happening incorrectly?

**Comment by pabloitu** [comment]
Ok super! Then the only issue is with the plotting. Two things happens:
- If cartopy receives the bbox as an extent, it will not display the first row and last column (northernmost row, easternmost column) of the forecast. 
- pyplot.pcolormesh and pyplot.pcolor, requires the grid encompassing the cell, or it ignores the last column of the forecast. 

https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.pcolormesh.html


But anyway, its easily fixable by extending the grid one dh further within the plot_spatial_dataset function. It works and I will include it in the next commit.

**Comment by wsavran** [comment]
that sounds like a reasonable fix to me. can you link the commit where you fix this to this issue?

**Comment by pabloitu** [comment]
Here. https://github.com/SCECcode/pycsep/blob/b8e38195adf39809ebdd61b183e0bb6e7521fc59/csep/utils/plots.py#L658

**Comment by wsavran** [comment]
nice. is that in the open pull request?

**Comment by pabloitu** [comment]
Yes!
