### ISSUE TITLE
S-test differences for same test catalog

### ISSUE THREAD

**Issue by kirstybayliss** [SCECcode/pycsep#59]
Using the Helmstetter example gridded forecasts and one of my own, I tried to compare S-test results and was surprised that the Helmstetter examples did poorly. This seems to be related to the spatial filtering step and the region associated with the test catalog, even when the regions have the same midpoints and the evaluation catalog contains the same events.

Comparing the midpoints for the two regions with `np.testing.assert_allclose` flags that they are different:

> Not equal to tolerance rtol=1e-07, atol=0
>
> Mismatched elements: 15287 / 15364 (99.5%)
> Max absolute difference: 11.600000000000009
> Max relative difference: 0.34850863422291994
>  x: array([[-125.35,   40.15],
>        [-125.35,   40.25],
>        [-125.35,   40.35],...
>  y: array([[-117.15,   31.55],
>       [-117.05,   31.55],
>       [-116.95,   31.55],...

I sorted the midpoint xs and ys and they are identical. Essentially my test forecasts and the example have different regions, though the sorted midpoints are the same. The filtered catalogs for the evaluation are also identical, but the s-tests results are very different. 

![Helmstetter_stest_comp](https://user-images.githubusercontent.com/37081055/100878759-81164a00-34a2-11eb-91ff-4375db1a2b97.png)

Do the regions maybe need some sorting somewhere for the spatial test? 

My test forecast:
[CSEP_test_forecast.txt](https://github.com/SCECcode/pycsep/files/5629630/CSEP_test_forecast.txt)

**Comment by wsavran** [comment]
in theory the regions should not need sorted for the spatial test. the test result for the shaded gray region seems to be the s-test result for the helmstetter model, [same as the example](https://docs.cseptesting.org/tutorials/gridded_forecast_evaluation.html). can you explain in a bit more detail how you created the bottom evaluation?

**Comment by kirstybayliss** [comment]
Yes, my problem is that I was trying to compare forecasts with different order of grid cells using one catalog, which I now understand I should not do! I had assumed that the region would be the same if the grid cells were the same and so it would be suitable to use one test catalog to compare forecasts. I was attempting to compare my own forecasts with the Helmstetter example and then used the Helmstetter example to illustrate my problem here, since the example on the website shows me what the result should be vs what I was getting. Sorry, I was not clear at all!

The bottom evaluation uses the same catalog as the example but filtered with the `test_forecast.region` from my `test_forecast` rather than the `forecast.region` in the example code, so it is the same catalog for the evaluation but the region is set up differently. 

So I was just doing this in my example above: 

    catalog = csep.query_comcat(forecast.start_time, forecast.end_time,
                                min_magnitude=forecast.min_magnitude)'
    
    cat1 = catalog.filter_spatial(forecast.region)
    cat2 = catalog.filter_spatial(test_forecast.region)

    spatial_test_result = poisson.spatial_test(forecast, cat1)
    spatial_test_result2 = poisson.spatial_test(forecast, cat2)

When I should have made a separate catalog to evaluate my test forecasts and used the original filtered catalog for the Helmstetter. It wasn't clear to me that this would result in major differences in the s-test given that the actual catalog I am using for the evaluation is exactly the same, this is because the evaluation uses the region information, right? So if it's not ordered in the same way, I'll get a bad result. I see now, thank you.

**Comment by wsavran** [comment]
that is a reasonable assumption, i'm going to leave this issue open and make a couple changes that should make this process more straightforward. thanks for sharing some more information about this. 

specifically, the function `filter_spatial` updates the state of the catalog meaning that the orignal `catalog` is changed after you call this function. this causes an issue when you call the function again. you can check the event count of `catalog` after the first `filter_spatial` call, to see what i'm talking about. 

i'm going to add an option called `in_place` to the function that produces a new catalog object and will allow you to use your code as written. i think this way makes more sense to me, and is consistent with the way the `filter` function works. 

in the mean time, you can 
```
import copy

catalog = csep.query_comcat(forecast.start_time, forecast.end_time,
                            min_magnitude=forecast.min_magnitude)

copy_catalog = copy.deepcopy(catalog)

cat1 = catalog....
cat2 = copy_catalog....
```
ill post here when ive made this modification.
