### ISSUE TITLE
adding plotting functionality for catalogs

### ISSUE THREAD

**Issue by wsavran** [SCECcode/pycsep#62]
catalogs should have an associated `.plot()` method that provides a simple interface to plot catalogs. the plot can be a simple in nature, but needs to handle arbitrary event locations. 

for example, a catalog of global events should be plotted on a different basemap than italian seismicity. eventually, the function should accept an arbitrary image layer such as a gridded forecast.

**Comment by pabloitu** [comment]
#64 Created blank PR. Please assign me to this issue

**Comment by wsavran** [comment]
done!

**Comment by wsavran** [comment]
closed with #64
