### ISSUE TITLE
warnings with numpy 1.20.1

### ISSUE THREAD

**Issue by wsavran** [SCECcode/pycsep#72]
test suite includes numerous warnings when running with numpy 1.20.1. this issue is a reminder that we need to keep an eye on this issue, because deprecation.

**Comment by pabloitu** [comment]
Also the `numpy` version requirement does not match with those found in `requirements.txt`, `requirements.yml`  (i.e. <1.21.5), causing error when compiling from source, as some dependencies install numpy==1.22.2. Suggest homogenize it, before we sort out this issue

https://github.com/SCECcode/pycsep/blob/ad217ed17d9da6965f0e75f6105f8f923820f7e9/setup.py#L29

**Comment by wsavran** [comment]
good catch. i've opened a pr with #185 that ill use to put together a new release. our conda feedstock has the correct version, so setup.py is the only remaining place this occurs. in the meantime you should be able to install via `conda` without issue.
