### ISSUE TITLE
magnitude bins on L and CL test

### ISSUE THREAD

**Issue by pabloitu** [SCECcode/pycsep#83]
In L and CL poisson tests, likelihood calculations throws error when `catalog` or `catalog.region` has no magnitude binning.
Should `catalog.spatial_magnitude_counts()` have  `gridded_forecast.mag_bins()` as arg?  Or the user must modify `catalog.region` to define its magnitude bins first?

https://github.com/SCECcode/pycsep/blob/a3c9d70cf8ba8f6d8177b48ad383b5675f90fa16/csep/core/poisson_evaluations.py#L307

https://github.com/SCECcode/pycsep/blob/a3c9d70cf8ba8f6d8177b48ad383b5675f90fa16/csep/core/poisson_evaluations.py#L177

**Comment by wsavran** [comment]
the region of the catalog and forecast must have magnitude bin information associated with it. right now i have been manually binding the forecast.region to the catalog object like 
```
catalog.region = forecast.region
```
but there are limitations to this approach. if you have a better idea on how that should work we could try and work it into the code.
