### ISSUE TITLE
time aware or not time aware

### ISSUE THREAD

**Issue by wsavran** [SCECcode/pycsep#85]
that is the question....

all times in pycsep are treated as being timezone aware with the timezone being set to UTC. before we adopt a wider user base we can rethink this decision. the major con is that using timezones can complicate issues and forces people to work with them directly. on the other hand, certain regions share their catalogs in local time coordinates instead of UTC. any thoughts on this? @pabloitu

**Comment by pabloitu** [comment]
The more I've been diving into different catalogs, I'm more convinced all internal methods should be default in UTC. But I agree this may be an issue in short-term models, where probably time windows (a day) are set by local TZ.   
Maybe I would think off giving options to (A) import in particular TZ, (B) filter by time in a determined TZ, but keeping the internal data in UTC for consistency (?)  

On the other hand,  the APIs to get QuakeML catalogs from Bolletino and the ISC returns in UTC which is really convenient. But im not sure if an option of TZ can be specified in the call.    
In either case, I believe we should eventually implement access to these Catalog APIs like with ComCat, and see from there how is the deal.

**Comment by wsavran** [comment]
closing for now, im not planning to change the timezones yet.
