### ISSUE TITLE
Writing mock class to directly plug-in gridded datasets to apply pycsep tests

### ISSUE THREAD

**Issue by khawajasim** [SCECcode/pycsep#91]
Hi,

I am integrating gridded catalog and gridded forecasts directly into the toolkit though mock classes, in order to use the tests built into the toolkit. Here are the mock classes. My datasets are mostly spatially gridded without magnitude bins. I needed opinion, whether the mock classes appear to be fine.
It appears to be working fine. However, I am just looking for external opinion. 

  class MyForecast:

    def __init__(self, data, name= 'my_forecast_class'):
            # initialize class data here….
            self.data = data
            self.name = name
            self.magnitudes = 5.95
            self.event_count = numpy.sum(data)

    def spatial_counts(self):
        
        """
        It would do return the spatial counts.
        Or if they are already 1D, retune the same data
        """
        
        if len(numpy.shape(self.data))>1:
            spatial_count = numpy.sum(self.data, axis = 1)
        else:
            spatial_count = self.data
        return spatial_count
    
    def event_count(self):
        """
        It would return total number of events in Gridded Forecast
        """
        return self.sum()
        
    class MyCatalog:
     
    def __init__(self, data, name='my_observed_catalog'):
          self.name = name
          self.data = data
          self.event_count = numpy.sum(data)

    def spatial_counts(self):
        
        """
        It would do return the spatial counts.
        Or if they are already 1D, retune the same data
        """
        
        if len(numpy.shape(self.data))>1:
            spatial_count = numpy.sum(self.data, axis = 1)
        else:
            spatial_count = self.data
        return spatial_count
     
    def event_count(self):
        """
        It would return total number of events in gridded Catalog
        """
        return self.sum()
    
        
    def spatial_magnitude_counts(self):
        """
        It would return same 2D numpy array 
        """   

        spatial_magnitude_count = self.data
        return spatial_magnitude_count

**Comment by wsavran** [comment]
they look fine to me, so long as data is placed into them in the correct form. with that being said, we will want to integrate the quadtree work as a new region that can be used to bin catalogs and do other useful operations. these mock classes are just to help interface with the evaluations. unless you have any other questions, can you close this issue?

**Comment by khawajasim** [comment]
So one more question. The data is mostly 1D numpy array with every value corresponds to the spatial rates. In my work, so far I have not been considering magnitude bins. So I run all my calculation for spatial bins. 

I believe this works fine. Would you agree?

**Comment by wsavran** [comment]
yes, this is fine for the spatial test.
