### ISSUE TITLE
Moment-magnitude relation in [reader.py]

### ISSUE THREAD

**Issue by hanbao-ucla** [SCECcode/pycsep#97]
Hi Bill

I'm here reporting a issue that I encountered when dealing with moment-magnitude relation.

When reading GCMT .ndk catalog, csep.utils.readers obtains the magnitude of an event based on the relation below:
`rec["Mw"] = 2.0 / 3.0 * (math.log10(rec["scalar_moment"]) - 9.10)`

However, USGS uses a slightly different one:
`rec["Mw"] = 2.0 / 3.0 * (math.log10(rec["scalar_moment"]) - 9.05)`

I'm wondering if you have noticed it or not. Or maybe there was discussion about which one to use before?

**Comment by wsavran** [comment]
Thanks for pointing that out. I followed the implementation of obspy for this reader function, so I somewhat blindly followed their lead. This isn't always true, but normally the gCMT catalog will be the main catalog stored in this format. Maybe a good solution would be to add an option to this reader function that will allow the user to choose. Ill implement this in an upcoming PR.
